language: node_js

node_js:
  - 7
  - 8
  - 10

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build
  - npm run test:ci
  
notifications:
  email:
    on_success: never
    on_failure: always