sudo: false
language: node_js

node_js:
  - 7
  - 8
  - 10

install:
  npm i -g yarn

before_script:
  - yarn install

cache:
  yarn: true
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build
  - npm run test:ci
  
notifications:
  email:
    on_success: never
    on_failure: always