# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

jobs:
   build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:10.10.0-jessie
    working_directory: ~/react-ts-starter
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
           # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Update yarn
          command: 'sudo npm i -g yarn@latest'
      - run:
          name: Global installation npx
          command: 'sudo npm i -g npx@latest'
      - run:
          name: Install npm
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test:ci
      - run:
          name: Build
          command: yarn build
      - deploy:
          name: deploy
          command: |
            if [ $CIRCLE_BRANCH = $SOURCE_BRANCH ]; then
              if [ $BUILD_TYPE = "firebase" ]; then
                npx firebase deploy --project $FIREBASE_PROJECT_ID --only hosting --token $FIREBASE_TOKEN
                npx firebase use --clear
              elif [ $BUILD_TYPE = "gh-pages" ]; then
                git config credential.helper 'cache --timeout=120'
                git config --global user.email $GITHUB_EMAIL
                git config --global user.name $GITHUB_USERNAME
                git config --global user.token $GH_TOKEN

                git clone https://${GH_TOKEN}@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git out

                cd out
                git checkout -b $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
                git rm -rf .
                cd ..

                npm run build

                cp -a build/. out/.

                mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
                cd out

                git add -A
                git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

                git push -q https://${GH_TOKEN}@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git $TARGET_BRANCH --force
              elif [ $BUILD_TYPE = "now" ]; then
                npm run build
                # cp -a build/. public/.
                npx now --static --token $NOW_TOKEN --local-config now.json
              elif [ $BUILD_TYPE = "netlify" ]; then  
                echo "BUILD TYPE >>>> $BUILD_TYPE"
              else
                echo "$BUILD_TYPE not in script"
              fi
            else
              echo "Not master branch, dry run only"
            fi