version: 2

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

defaults: &defaults
  working_directory: ~/react-ts-starter
  docker:
    - image: circleci/node:10.10.0-jessie

jobs:
  prepare:
    <<: *defaults
    steps:
      - *attach_workspace
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Update yarn
          command: 'sudo npm i -g yarn@latest'
      - run:
          name: Install npm
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - *attach_workspace
      - checkout
      - run: yarn build

  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Lint
          command: yarn lint

  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Test
          command: yarn test:ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - lint:
          requires:
            - prepare
            - build
      - test:
          requires:
            - prepare
            - build
          filters:
            branches:
              only: master