# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

jobs:
   build:
    docker:
      - image: circleci/node:8.2.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
           # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Update yarn
          command: 'sudo npm i -g yarn@latest'
      - run:
          name: Install npm
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test:ci
      - run:
          name: Build
          command: yarn build