version: 2
jobs:
  build:
    working_directory: ~/react-ts-starter
    docker:
      - image: circleci/node:10.10.0-jessie
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Update yarn
          command: 'sudo npm i -g yarn@latest'
      - run:
          name: Install npm wee
          command: npx yarn install
      - run:
          name: Install npm wee
          command: npx yarn run build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/node:10.10.0-jessie
    steps:
      - checkout
      - run:
          name: Lint
          command: npx yarn run lint
  test:
    docker:
      - image: circleci/node:10.10.0-jessie
    steps:
      - checkout
      - run:
          name: Test
          command: npx yarn run test:ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - lint:
          requires:
            - build
          filters:
            branches:
              only: master